# Generated by Django 3.1.5 on 2021-02-08 07:10

import app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y', validators=[app.validators.file_size])),
                ('likes', models.ManyToManyField(related_name='blog_posts1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img/%y', validators=[app.validators.file_size])),
                ('likes', models.ManyToManyField(related_name='blog_posts2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='file/%y', validators=[app.validators.file_size])),
                ('likes', models.ManyToManyField(related_name='blog_posts3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
