# Generated by Django 3.1.5 on 2021-02-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210211_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
    ]
