# Generated by Django 3.1.5 on 2021-02-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_video_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
    ]
